name: Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: cd apps/wilakers && pnpm install

      - name: Build front-end
        run:  cd apps/wilakers && pnpm wilakers:build
 
      - name: Deploy front-end to S3 bucket
        run: aws s3 sync  cd apps/wilakers/dist/ s3://wilakers.com --delete

      # - name: Invalidate CloudFront files
      #   run: aws cloudfront create-invalidation --distribution-id <replace me> --paths '/*'
